/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certificate {
  'traineeName' : string,
  'instituteName' : string,
  'trade' : string,
  'trainingEndDate' : string,
  'fatherName' : string,
  'instituteAddress' : string,
  'trainingStartDate' : string,
  'certified' : boolean,
  'certificateIssueDate' : string,
  'certificateNumber' : string,
}
export type CertificateId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCertificate' : ActorMethod<[Certificate], CertificateId>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCertificate' : ActorMethod<[CertificateId], Certificate>,
  'getCertificateByNumber' : ActorMethod<[string], Certificate>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCertificates' : ActorMethod<[], Array<Certificate>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCertificate' : ActorMethod<[CertificateId, Certificate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];