/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Certificate = IDL.Record({
  'traineeName' : IDL.Text,
  'instituteName' : IDL.Text,
  'trade' : IDL.Text,
  'trainingEndDate' : IDL.Text,
  'fatherName' : IDL.Text,
  'instituteAddress' : IDL.Text,
  'trainingStartDate' : IDL.Text,
  'certified' : IDL.Bool,
  'certificateIssueDate' : IDL.Text,
  'certificateNumber' : IDL.Text,
});
export const CertificateId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCertificate' : IDL.Func([Certificate], [CertificateId], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCertificate' : IDL.Func([CertificateId], [Certificate], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCertificate' : IDL.Func([CertificateId, Certificate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Certificate = IDL.Record({
    'traineeName' : IDL.Text,
    'instituteName' : IDL.Text,
    'trade' : IDL.Text,
    'trainingEndDate' : IDL.Text,
    'fatherName' : IDL.Text,
    'instituteAddress' : IDL.Text,
    'trainingStartDate' : IDL.Text,
    'certified' : IDL.Bool,
    'certificateIssueDate' : IDL.Text,
    'certificateNumber' : IDL.Text,
  });
  const CertificateId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCertificate' : IDL.Func([Certificate], [CertificateId], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCertificate' : IDL.Func([CertificateId], [Certificate], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCertificate' : IDL.Func([CertificateId, Certificate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };